name: CI/CD for Next.js

on:
  push:
    branches: [ feature/* ] # 各ブランチへの push で実行
  pull_request:
    types: [closed]   # PR が閉じられた時 -> マージされた時
    branches: [ main ] # main 向けの PR のみ

jobs:
  ci:
    name: Run Lint & Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Clear npm cache
        run: npm cache clean --force
      
      - name: Install dependencies
        run: |
          rm -f package-lock.json
          rm -rf node_modules
          npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Jest tests
        run: npm test

      - name: Build project
        run: npm run build

  cd:
    if: github.event.pull_request.merged == true  # マージされた場合のみ
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js (for build)
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies for deployment
        run: |
          npm cache clean --force
          rm -f package-lock.json
          npm install --legacy-peer-deps --registry https://registry.npmjs.org/

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}        # 必須
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}      # 必須
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }} # 必須
          vercel-args: '--prod'   # 本番に反映するため必須
          working-directory: ./
